# Generated by Django 4.2.5 on 2023-11-11 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('salary_from', models.FloatField(null=True)),
                ('salary_to', models.FloatField(null=True)),
                ('working_time_from', models.IntegerField()),
                ('working_time_to', models.IntegerField()),
                ('experience_year', models.FloatField(null=True)),
                ('description', models.TextField()),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
                ('deadline', models.DateField(null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('requests', models.ManyToManyField(related_name='vacancy_resumes', through='resumes.VacancyResume', to='resumes.resumes')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='VacancySkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.skills')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.vacancies')),
            ],
        ),
        migrations.AddField(
            model_name='vacancies',
            name='requirements',
            field=models.ManyToManyField(through='vacancies.VacancySkills', to='skills.skills'),
        ),
    ]
