# Generated by Django 4.2.5 on 2023-11-11 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0001_initial'),
        ('skills', '0001_initial'),
        ('vacancies', '0001_initial'),
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyresume',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.vacancies'),
        ),
        migrations.AddField(
            model_name='resumeskills',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resumes.resumes'),
        ),
        migrations.AddField(
            model_name='resumeskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.skills'),
        ),
        migrations.AddField(
            model_name='resumes',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumes',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professions.professions'),
        ),
        migrations.AddField(
            model_name='resumes',
            name='skills',
            field=models.ManyToManyField(through='resumes.ResumeSkills', to='skills.skills'),
        ),
        migrations.AddField(
            model_name='resumes',
            name='vacancies',
            field=models.ManyToManyField(through='resumes.VacancyResume', to='vacancies.vacancies'),
        ),
    ]
